import re
from typing import List, Dict, Any
from sqlalchemy.orm import Session
from app.models.vocabulary import Vocabulary


APTIS_HIGH_LEVEL_VOCABULARY: List[Dict[str, Any]] = [
    # =========================================================================
    # LEVEL B1 (Trung cấp - Trọng tâm Aptis B1)
    # =========================================================================
    {
        "word": "accommodation",
        "phonetic": "/əˌkɒm.əˈdeɪ.ʃən/",
        "pos": "noun",
        "meaning_vi": "Nơi ở, chỗ lưu trú (khách sạn, trọ)",
        "cefr_level": "B1",
        "skill": "reading",
        "category": "Travel & Transport",
        "example_en": "The hotel provides luxury accommodation for visiting tourists.",
        "example_vi": "Khách sạn cung cấp chỗ ở sang trọng cho du khách đến thăm.",
        "synonyms": "lodging, housing",
        "occurrences": 24
    },
    {
        "word": "itinerary",
        "phonetic": "/aɪˈtɪn.ər.ər.i/",
        "pos": "noun",
        "meaning_vi": "Lịch trình chi tiết chuyến đi",
        "cefr_level": "B1",
        "skill": "reading",
        "category": "Travel & Transport",
        "example_en": "The tour guide handed us a detailed itinerary of the 5-day trip.",
        "example_vi": "Hướng dẫn viên du lịch đã trao cho chúng tôi lịch trình chi tiết của chuyến đi 5 ngày.",
        "synonyms": "travel plan, schedule",
        "occurrences": 18
    },
    {
        "word": "applicant",
        "phonetic": "/ˈæp.lɪ.kənt/",
        "pos": "noun",
        "meaning_vi": "Ứng viên xin việc",
        "cefr_level": "B1",
        "skill": "reading",
        "category": "Work & Business",
        "example_en": "The successful applicant will start work next month.",
        "example_vi": "Ứng viên trúng tuyển sẽ bắt đầu làm việc vào tháng tới.",
        "synonyms": "candidate, job seeker",
        "occurrences": 19
    },
    {
        "word": "souvenir",
        "phonetic": "/ˌsuː.vənˈɪər/",
        "pos": "noun",
        "meaning_vi": "Quà lưu niệm",
        "cefr_level": "B1",
        "skill": "reading",
        "category": "Travel & Transport",
        "example_en": "I bought a handcrafted silk scarf as a souvenir from Hoi An.",
        "example_vi": "Tôi đã mua một chiếc khăn lụa thủ công làm quà lưu niệm từ Hội An.",
        "synonyms": "keepsake, memento",
        "occurrences": 14
    },
    {
        "word": "luggage",
        "phonetic": "/ˈlʌɡ.ɪdʒ/",
        "pos": "noun",
        "meaning_vi": "Hành lý",
        "cefr_level": "B1",
        "skill": "listening",
        "category": "Travel & Transport",
        "example_en": "Passengers are allowed to carry two pieces of hand luggage.",
        "example_vi": "Hành khách được phép mang theo hai kiện hành lý xách tay.",
        "synonyms": "baggage, belongings",
        "occurrences": 19
    },
    {
        "word": "annual",
        "phonetic": "/ˈæn.ju.əl/",
        "pos": "adjective",
        "meaning_vi": "Hàng năm",
        "cefr_level": "B1",
        "skill": "grammar",
        "category": "Work & Business",
        "example_en": "The company holds its annual meeting every December.",
        "example_vi": "Công ty tổ chức cuộc họp hàng năm vào mỗi tháng 12.",
        "synonyms": "yearly",
        "occurrences": 23
    },
    {
        "word": "inconvenience",
        "phonetic": "/ˌɪn.kənˈviː.ni.əns/",
        "pos": "noun",
        "meaning_vi": "Sự phiền ngoái, bất tiện",
        "cefr_level": "B1",
        "skill": "writing",
        "category": "Work & Business",
        "example_en": "We apologize for any inconvenience caused by the technical error.",
        "example_vi": "Chúng tôi xin lỗi vì bất kỳ sự phiền ngoái nào gây ra bởi lỗi kỹ thuật.",
        "synonyms": "trouble, bother",
        "occurrences": 26
    },
    {
        "word": "destination",
        "phonetic": "/ˌdes.tɪˈneɪ.ʃən/",
        "pos": "noun",
        "meaning_vi": "Điểm đến",
        "cefr_level": "B1",
        "skill": "reading",
        "category": "Travel & Transport",
        "example_en": "Da Nang is a popular tourist destination in Vietnam.",
        "example_vi": "Đà Nẵng là một điểm đến du lịch nổi tiếng tại Việt Nam.",
        "synonyms": "stop, location",
        "occurrences": 17
    },
    {
        "word": "reservation",
        "phonetic": "/ˌrez.əˈveɪ.ʃən/",
        "pos": "noun",
        "meaning_vi": "Sự đặt chỗ trước",
        "cefr_level": "B1",
        "skill": "listening",
        "category": "Travel & Transport",
        "example_en": "I would like to cancel my hotel reservation for tonight.",
        "example_vi": "Tôi muốn hủy đặt phòng khách sạn cho tối nay.",
        "synonyms": "booking",
        "occurrences": 21
    },
    {
        "word": "departure",
        "phonetic": "/dɪˈpɑː.tʃər/",
        "pos": "noun",
        "meaning_vi": "Giờ xuất phát, sự khởi hành",
        "cefr_level": "B1",
        "skill": "listening",
        "category": "Travel & Transport",
        "example_en": "Please check the departure board for your flight status.",
        "example_vi": "Vui lòng kiểm tra bảng giờ khởi hành để biết trạng thái chuyến bay.",
        "synonyms": "leaving, exit",
        "occurrences": 16
    },
    {
        "word": "supervisor",
        "phonetic": "/ˈsuː.pə.vaɪ.zər/",
        "pos": "noun",
        "meaning_vi": "Người giám sát",
        "cefr_level": "B1",
        "skill": "listening",
        "category": "Work & Business",
        "example_en": "Report any equipment issues to your supervisor immediately.",
        "example_vi": "Báo cáo bất kỳ sự cố thiết bị nào cho người giám sát của bạn ngay lập tức.",
        "synonyms": "manager, boss",
        "occurrences": 18
    },
    {
        "word": "promotion",
        "phonetic": "/prəˈməʊ.ʃən/",
        "pos": "noun",
        "meaning_vi": "Sự thăng tiến công việc",
        "cefr_level": "B1",
        "skill": "reading",
        "category": "Work & Business",
        "example_en": "Her hard work earned her a promotion to senior manager.",
        "example_vi": "Sự chăm chỉ của cô ấy đã giúp cô nhận được sự thăng tiến lên quản lý cấp cao.",
        "synonyms": "advancement, upgrade",
        "occurrences": 18
    },
    {
        "word": "passionate",
        "phonetic": "/ˈpæʃ.ən.ət/",
        "pos": "adjective",
        "meaning_vi": "Đam đam, nhiệt huyết",
        "cefr_level": "B1",
        "skill": "speaking",
        "category": "Education & Learning",
        "example_en": "I am passionate about music and learning acoustic guitar.",
        "example_vi": "Tôi đam mê âm nhạc và học chơi đàn guitar acoustic.",
        "synonyms": "enthusiastic, eager",
        "occurrences": 22
    },
    {
        "word": "recommendation",
        "phonetic": "/ˌrek.ə.menˈdeɪ.ʃən/",
        "pos": "noun",
        "meaning_vi": "Lời giới thiệu, đề xuất",
        "cefr_level": "B1",
        "skill": "reading",
        "category": "Education & Learning",
        "example_en": "Can you give me a recommendation for a good local restaurant?",
        "example_vi": "Bạn có thể cho tôi lời gợi ý về một nhà hàng địa phương ngon không?",
        "synonyms": "suggestion, advice",
        "occurrences": 17
    },
    {
        "word": "assignment",
        "phonetic": "/əˈsaɪn.mənt/",
        "pos": "noun",
        "meaning_vi": "Bài tập lớn, nhiệm vụ",
        "cefr_level": "B1",
        "skill": "writing",
        "category": "Education & Learning",
        "example_en": "Students must submit their essay assignment by Friday.",
        "example_vi": "Học sinh phải nộp bài tập luận văn trước thứ Sáu.",
        "synonyms": "task, project",
        "occurrences": 19
    },
    {
        "word": "complaint",
        "phonetic": "/kəmˈpleɪnt/",
        "pos": "noun",
        "meaning_vi": "Lời phàn nàn, khiếu nại (Writing Part 4)",
        "cefr_level": "B1",
        "skill": "writing",
        "category": "Work & Business",
        "example_en": "I am writing to make a formal complaint about the service.",
        "example_vi": "Tôi viết thư này để đưa ra lời phàn nàn chính thức về dịch vụ.",
        "synonyms": "grievance, protest",
        "occurrences": 25
    },
    {
        "word": "apologize",
        "phonetic": "/əˈpɒl.ə.dʒaɪz/",
        "pos": "verb",
        "meaning_vi": "Xin lỗi trang trọng",
        "cefr_level": "B1",
        "skill": "writing",
        "category": "Work & Business",
        "example_en": "I sincerely apologize for the delay in sending the report.",
        "example_vi": "Tôi chân thành xin lỗi vì sự chậm trễ trong việc gửi báo cáo.",
        "synonyms": "express regret",
        "occurrences": 23
    },
    {
        "word": "refund",
        "phonetic": "/ˈriː.fʌnd/",
        "pos": "noun",
        "meaning_vi": "Sự hoàn tiền",
        "cefr_level": "B1",
        "skill": "writing",
        "category": "Work & Business",
        "example_en": "I would like to request a full refund for my ticket.",
        "example_vi": "Tôi muốn yêu cầu hoàn tiền đầy đủ cho chiếc vé của mình.",
        "synonyms": "reimbursement",
        "occurrences": 20
    },
    {
        "word": "opportunity",
        "phonetic": "/ˌɒp.əˈtʃuː.nə.ti/",
        "pos": "noun",
        "meaning_vi": "Cơ hội tốt",
        "cefr_level": "B1",
        "skill": "writing",
        "category": "Education & Learning",
        "example_en": "Joining the club gives me a great opportunity to practice English.",
        "example_vi": "Tham gia câu lạc bộ cho tôi cơ hội tuyệt vời để luyện tập tiếng Anh.",
        "synonyms": "chance, opening",
        "occurrences": 27
    },
    {
        "word": "participate",
        "phonetic": "/pɑːˈtɪs.ɪ.peɪt/",
        "pos": "verb",
        "meaning_vi": "Tham gia vào sự kiện",
        "cefr_level": "B1",
        "skill": "speaking",
        "category": "Daily Life",
        "example_en": "Many students participate in outdoor sports activities.",
        "example_vi": "Nhiều học sinh tham gia các hoạt động thể thao ngoài trời.",
        "synonyms": "take part, join",
        "occurrences": 24
    },

    # =========================================================================
    # LEVEL B2 (Trung cấp cao - Bứt phá B2)
    # =========================================================================
    {
        "word": "commence",
        "phonetic": "/kəˈmens/",
        "pos": "verb",
        "meaning_vi": "Bắt đầu, khởi công (trang trọng)",
        "cefr_level": "B2",
        "skill": "grammar",
        "category": "Work & Business",
        "example_en": "The conference will commence at 9 AM tomorrow.",
        "example_vi": "Hội nghị sẽ bắt đầu lúc 9 giờ sáng mai.",
        "synonyms": "begin, start, launch",
        "occurrences": 14
    },
    {
        "word": "qualifications",
        "phonetic": "/ˌkwɒl.ɪ.fɪˈkeɪ.ʃənz/",
        "pos": "noun",
        "meaning_vi": "Bằng cấp, năng lực chuyên môn",
        "cefr_level": "B2",
        "skill": "reading",
        "category": "Work & Business",
        "example_en": "Candidates should possess suitable professional qualifications.",
        "example_vi": "Các ứng viên nên có bằng cấp chuyên môn phù hợp.",
        "synonyms": "degrees, credentials",
        "occurrences": 16
    },
    {
        "word": "implement",
        "phonetic": "/ˈɪm.plɪ.ment/",
        "pos": "verb",
        "meaning_vi": "Thực hiện, áp dụng chính sách",
        "cefr_level": "B2",
        "skill": "reading",
        "category": "Work & Business",
        "example_en": "The firm plans to implement a new remote work policy.",
        "example_vi": "Công ty có kế hoạch áp dụng chính sách làm việc từ xa mới.",
        "synonyms": "execute, enforce",
        "occurrences": 17
    },
    {
        "word": "substantially",
        "phonetic": "/səbˈstæn.ʃəl.i/",
        "pos": "adverb",
        "meaning_vi": "Đáng kể",
        "cefr_level": "B2",
        "skill": "reading",
        "category": "Work & Business",
        "example_en": "Profits have grown substantially this quarter.",
        "example_vi": "Lợi nhuận đã tăng trưởng đáng kể trong quý này.",
        "synonyms": "significantly, considerably",
        "occurrences": 20
    },
    {
        "word": "negotiate",
        "phonetic": "/nəˈɡəʊ.ʃi.eɪt/",
        "pos": "verb",
        "meaning_vi": "Đàm phán, thương lượng",
        "cefr_level": "B2",
        "skill": "reading",
        "category": "Work & Business",
        "example_en": "We managed to negotiate a lower price for the contract.",
        "example_vi": "Chúng tôi đã đàm phán được mức giá thấp hơn cho hợp đồng.",
        "synonyms": "bargain, discuss",
        "occurrences": 13
    },
    {
        "word": "resignation",
        "phonetic": "/ˌrez.ɪɡˈneɪ.ʃən/",
        "pos": "noun",
        "meaning_vi": "Đơn xin thôi việc, sự từ chức",
        "cefr_level": "B2",
        "skill": "writing",
        "category": "Work & Business",
        "example_en": "The director tendered his resignation yesterday.",
        "example_vi": "Giám đốc đã nộp đơn xin từ chức vào ngày hôm qua.",
        "synonyms": "departure, step-down",
        "occurrences": 11
    },
    {
        "word": "productivity",
        "phonetic": "/ˌprɒd.ʌkˈtɪv.ə.ti/",
        "pos": "noun",
        "meaning_vi": "Năng suất làm việc",
        "cefr_level": "B2",
        "skill": "reading",
        "category": "Work & Business",
        "example_en": "Good working conditions boost employee productivity.",
        "example_vi": "Điều kiện làm việc tốt sẽ thúc đẩy năng suất của nhân viên.",
        "synonyms": "output, efficiency",
        "occurrences": 15
    },
    {
        "word": "strategy",
        "phonetic": "/ˈstræt.ə.dʒi/",
        "pos": "noun",
        "meaning_vi": "Chiến lược",
        "cefr_level": "B2",
        "skill": "reading",
        "category": "Work & Business",
        "example_en": "The team adopted a new marketing strategy.",
        "example_vi": "Nhóm đã áp dụng một chiến lược tiếp thị mới.",
        "synonyms": "plan, approach",
        "occurrences": 18
    },
    {
        "word": "curriculum",
        "phonetic": "/kəˈrɪk.jə.ləm/",
        "pos": "noun",
        "meaning_vi": "Chương trình giảng dạy",
        "cefr_level": "B2",
        "skill": "reading",
        "category": "Education & Learning",
        "example_en": "The school updated its curriculum to include coding classes.",
        "example_vi": "Trường học đã cập nhật chương trình giảng dạy bao gồm các lớp học lập trình.",
        "synonyms": "syllabus, course of study",
        "occurrences": 14
    },
    {
        "word": "evaluate",
        "phonetic": "/ɪˈvæl.ju.eɪt/",
        "pos": "verb",
        "meaning_vi": "Đánh giá, chấm điểm",
        "cefr_level": "B2",
        "skill": "speaking",
        "category": "Education & Learning",
        "example_en": "Examiners evaluate your speaking skills based on four criteria.",
        "example_vi": "Giám khảo đánh giá kỹ năng nói của bạn dựa trên bốn tiêu chí.",
        "synonyms": "assess, judge, score",
        "occurrences": 16
    },
    {
        "word": "fluency",
        "phonetic": "/ˈfluː.ən.si/",
        "pos": "noun",
        "meaning_vi": "Sự trôi chảy trong giao tiếp",
        "cefr_level": "B2",
        "skill": "speaking",
        "category": "Education & Learning",
        "example_en": "Practice helps you improve fluency and confidence.",
        "example_vi": "Luyện tập giúp bạn cải thiện sự trôi chảy và tự tin.",
        "synonyms": "articulateness, flow",
        "occurrences": 17
    },
    {
        "word": "appreciate",
        "phonetic": "/əˈpriː.ʃi.eɪt/",
        "pos": "verb",
        "meaning_vi": "Trân trọng, cảm kích",
        "cefr_level": "B2",
        "skill": "writing",
        "category": "Work & Business",
        "example_en": "I would greatly appreciate it if you could reply promptly.",
        "example_vi": "Tôi sẽ rất cảm kích nếu bạn có thể phản hồi sớm.",
        "synonyms": "value, treasure",
        "occurrences": 21
    },
    {
        "word": "dissatisfied",
        "phonetic": "/dɪsˈsæt.ɪs.faɪd/",
        "pos": "adjective",
        "meaning_vi": "Không hài lòng, bất mãn",
        "cefr_level": "B2",
        "skill": "writing",
        "category": "Work & Business",
        "example_en": "I am extremely dissatisfied with the quality of the product.",
        "example_vi": "Tôi cực kỳ không hài lòng với chất lượng của sản phẩm.",
        "synonyms": "unhappy, displeased",
        "occurrences": 19
    },
    {
        "word": "perspective",
        "phonetic": "/pəˈspek.tɪv/",
        "pos": "noun",
        "meaning_vi": "Góc nhìn, quan điểm cá nhân",
        "cefr_level": "B2",
        "skill": "speaking",
        "category": "Environment & Society",
        "example_en": "From my perspective, studying abroad broadens one's horizon.",
        "example_vi": "Theo góc nhìn của tôi, du học mở rộng tầm mắt của một người.",
        "synonyms": "viewpoint, opinion",
        "occurrences": 19
    },
    {
        "word": "picturesque",
        "phonetic": "/ˌpɪk.tʃərˈesk/",
        "pos": "adjective",
        "meaning_vi": "Đẹp như tranh vẽ (mô tả tranh Speaking Part 2)",
        "cefr_level": "B2",
        "skill": "speaking",
        "category": "Daily Life",
        "example_en": "In the photo, I can see a picturesque village by the mountain.",
        "example_vi": "Trong bức ảnh, tôi có thể thấy một ngôi làng đẹp như tranh vẽ bên núi.",
        "synonyms": "scenic, charming",
        "occurrences": 15
    },
    {
        "word": "bustling",
        "phonetic": "/ˈbʌs.lɪŋ/",
        "pos": "adjective",
        "meaning_vi": "Sầm uất, nhộn nhịp",
        "cefr_level": "B2",
        "skill": "speaking",
        "category": "Daily Life",
        "example_en": "Hanoi is a bustling city with vibrant street markets.",
        "example_vi": "Hà Nội là một thành phố sầm uất với các khu chợ đường phố nhộn nhịp.",
        "synonyms": "lively, busy",
        "occurrences": 18
    },
    {
        "word": "hospitality",
        "phonetic": "/ˌhɒs.pɪˈtæl.ə.ti/",
        "pos": "noun",
        "meaning_vi": "Sự hiếu khách, lòng mến khách",
        "cefr_level": "B2",
        "skill": "speaking",
        "category": "Daily Life",
        "example_en": "The local people greeted us with warm hospitality.",
        "example_vi": "Người dân địa phương đã chào đón chúng tôi bằng sự hiếu khách ấm áp.",
        "synonyms": "warmth, friendliness",
        "occurrences": 14
    },
    {
        "word": "guarantee",
        "phonetic": "/ˌɡær.ənˈtiː/",
        "pos": "noun",
        "meaning_vi": "Sự bảo hành, bảo đảm",
        "cefr_level": "B2",
        "skill": "listening",
        "category": "Work & Business",
        "example_en": "The appliance comes with a two-year money-back guarantee.",
        "example_vi": "Thiết bị này đi kèm với chế độ bảo hành hoàn tiền trong hai năm.",
        "synonyms": "assurance, warranty",
        "occurrences": 16
    },
    {
        "word": "transformation",
        "phonetic": "/ˌtræns.fəˈmeɪ.ʃən/",
        "pos": "noun",
        "meaning_vi": "Sự biến đổi toàn diện",
        "cefr_level": "B2",
        "skill": "reading",
        "category": "Technology & Science",
        "example_en": "AI is driving the digital transformation of education.",
        "example_vi": "AI đang thúc đẩy sự chuyển đổi số của giáo dục.",
        "synonyms": "change, revolution",
        "occurrences": 21
    },
    {
        "word": "innovation",
        "phonetic": "/ˌɪn.əˈveɪ.ʃən/",
        "pos": "noun",
        "meaning_vi": "Sự đổi mới, sáng tạo",
        "cefr_level": "B2",
        "skill": "reading",
        "category": "Technology & Science",
        "example_en": "Technological innovation improves our quality of life.",
        "example_vi": "Sự đổi mới công nghệ nâng cao chất lượng cuộc sống của chúng ta.",
        "synonyms": "invention, novelty",
        "occurrences": 18
    },
    {
        "word": "automate",
        "phonetic": "/ˈɔː.tə.meɪt/",
        "pos": "verb",
        "meaning_vi": "Tự động hóa",
        "cefr_level": "B2",
        "skill": "grammar",
        "category": "Technology & Science",
        "example_en": "Businesses automate repetitive tasks to save time.",
        "example_vi": "Các doanh nghiệp tự động hóa các nhiệm vụ lặp đi lặp lại để tiết kiệm thời gian.",
        "synonyms": "computerize",
        "occurrences": 15
    },
    {
        "word": "breakthrough",
        "phonetic": "/ˈbreɪk.θruː/",
        "pos": "noun",
        "meaning_vi": "Bước đột phá lớn",
        "cefr_level": "B2",
        "skill": "reading",
        "category": "Technology & Science",
        "example_en": "Scientists achieved a major medical breakthrough in cancer treatment.",
        "example_vi": "Các nhà khoa học đã đạt được một bước đột phá y khoa lớn trong điều trị ung thư.",
        "synonyms": "advance, discovery",
        "occurrences": 13
    },
    {
        "word": "environmentally friendly",
        "phonetic": "/ɪnˌvaɪ.rənˈmen.təl.i ˈfrend.li/",
        "pos": "collocation",
        "meaning_vi": "Thân thiện với môi trường",
        "cefr_level": "B2",
        "skill": "writing",
        "category": "Environment & Society",
        "example_en": "Solar energy is an environmentally friendly power source.",
        "example_vi": "Năng lượng mặt trời là một nguồn năng lượng thân thiện với môi trường.",
        "synonyms": "eco-friendly, green",
        "occurrences": 19
    },
    {
        "word": "sustainable",
        "phonetic": "/səˈsteɪ.nə.bəl/",
        "pos": "adjective",
        "meaning_vi": "Bền vững",
        "cefr_level": "B2",
        "skill": "reading",
        "category": "Environment & Society",
        "example_en": "We need sustainable solutions for plastic waste management.",
        "example_vi": "Chúng ta cần các giải pháp bền vững cho việc quản lý rác thải nhựa.",
        "synonyms": "renewable, eco-friendly",
        "occurrences": 17
    },
    {
        "word": "conservation",
        "phonetic": "/ˌkɒn.səˈveɪ.ʃən/",
        "pos": "noun",
        "meaning_vi": "Sự bảo tồn thiên nhiên",
        "cefr_level": "B2",
        "skill": "reading",
        "category": "Environment & Society",
        "example_en": "Wildlife conservation programs help protect endangered species.",
        "example_vi": "Các chương trình bảo tồn động vật hoang dã giúp bảo vệ các loài có nguy cơ tuyệt chủng.",
        "synonyms": "protection, preservation",
        "occurrences": 16
    },
    {
        "word": "biodiversity",
        "phonetic": "/ˌbaɪ.əʊ.daɪˈvɜː.sə.ti/",
        "pos": "noun",
        "meaning_vi": "Đa dạng sinh học",
        "cefr_level": "B2",
        "skill": "reading",
        "category": "Environment & Society",
        "example_en": "Rainforests are famous for their rich biodiversity.",
        "example_vi": "Rừng mưa nhiệt đới nổi tiếng với sự đa dạng sinh học phong phú.",
        "synonyms": "ecological variety",
        "occurrences": 12
    },
    {
        "word": "contribute to",
        "phonetic": "/kənˈtrɪb.juːt tuː/",
        "pos": "phrasal verb",
        "meaning_vi": "Đóng góp vào",
        "cefr_level": "B2",
        "skill": "writing",
        "category": "Collocations & Idioms",
        "example_en": "Teamwork contributes to project success.",
        "example_vi": "Làm việc nhóm đóng góp vào sự thành công của dự án.",
        "synonyms": "lead to, add to",
        "occurrences": 22
    },
    {
        "word": "take advantage of",
        "phonetic": "/teɪk ədˈvɑːn.tɪdʒ ɒv/",
        "pos": "collocation",
        "meaning_vi": "Tận dụng cơ hội",
        "cefr_level": "B2",
        "skill": "reading",
        "category": "Collocations & Idioms",
        "example_en": "Take advantage of the library books to enrich your knowledge.",
        "example_vi": "Hãy tận dụng sách thư viện để làm giàu kiến thức của bạn.",
        "synonyms": "make use of",
        "occurrences": 20
    },
    {
        "word": "consequently",
        "phonetic": "/ˈkɒn.sɪ.kwənt.li/",
        "pos": "adverb",
        "meaning_vi": "Do đó, hậu quả là",
        "cefr_level": "B2",
        "skill": "grammar",
        "category": "Core Grammar",
        "example_en": "The road was blocked; consequently, traffic was delayed.",
        "example_vi": "Con đường đã bị phong tỏa; do đó, giao thông bị trễ.",
        "synonyms": "therefore, as a result",
        "occurrences": 24
    },
    {
        "word": "nevertheless",
        "phonetic": "/ˌnev.ə.ðəˈles/",
        "pos": "adverb",
        "meaning_vi": "Tuy nhiên, mặc dù vậy",
        "cefr_level": "B2",
        "skill": "grammar",
        "category": "Core Grammar",
        "example_en": "It was late; nevertheless, she kept working on her report.",
        "example_vi": "Đã muộn; tuy nhiên, cô ấy vẫn tiếp tục làm việc với báo cáo của mình.",
        "synonyms": "however, nonetheless",
        "occurrences": 25
    },
    {
        "word": "excursion",
        "phonetic": "/ɪkˈskɜː.ʃən/",
        "pos": "noun",
        "meaning_vi": "Chuyến tham quan dã ngoại ngắn ngày",
        "cefr_level": "B2",
        "skill": "reading",
        "category": "Travel & Transport",
        "example_en": "The hotel organizes daily boat excursions to nearby islands.",
        "example_vi": "Khách sạn tổ chức các chuyến tham quan bằng thuyền hàng ngày đến các đảo lân cận.",
        "synonyms": "trip, outing",
        "occurrences": 14
    },

    # =========================================================================
    # LEVEL C1 & C2 (Cao cấp Aptis Advanced)
    # =========================================================================
    {
        "word": "unprecedented",
        "phonetic": "/ʌnˈpres.ɪ.den.tɪd/",
        "pos": "adjective",
        "meaning_vi": "Chưa từng có tiền lệ",
        "cefr_level": "C1",
        "skill": "reading",
        "category": "Technology & Science",
        "example_en": "Technology develops at an unprecedented pace.",
        "example_vi": "Công nghệ phát triển với tốc độ chưa từng có tiền lệ.",
        "synonyms": "extraordinary, unmatched",
        "occurrences": 11
    },
    {
        "word": "indispensable",
        "phonetic": "/ˌɪn.dɪˈspen.sə.bəl/",
        "pos": "adjective",
        "meaning_vi": "Không thể thiếu",
        "cefr_level": "C1",
        "skill": "writing",
        "category": "Technology & Science",
        "example_en": "Smartphones are indispensable tools in daily communication.",
        "example_vi": "Điện thoại thông minh là công cụ không thể thiếu trong giao tiếp hàng ngày.",
        "synonyms": "essential, vital",
        "occurrences": 13
    },
    {
        "word": "deteriorate",
        "phonetic": "/dɪˈtɪə.ri.ə.reɪt/",
        "pos": "verb",
        "meaning_vi": "Suy giảm, mấu tệ đi",
        "cefr_level": "C1",
        "skill": "reading",
        "category": "Environment & Society",
        "example_en": "Air quality will deteriorate if emissions are not reduced.",
        "example_vi": "Chất lượng không khí sẽ suy giảm nếu lượng khí thải không được giảm thiểu.",
        "synonyms": "worsen, decline",
        "occurrences": 12
    },
    {
        "word": "alleviate",
        "phonetic": "/əˈliː.vi.eɪt/",
        "pos": "verb",
        "meaning_vi": "Xoa dịu, làm giảm bớt (tắc nghẽn, áp lực, nỗi đau)",
        "cefr_level": "C1",
        "skill": "reading",
        "category": "Health & Lifestyle",
        "example_en": "The new bypass road aims to alleviate traffic congestion.",
        "example_vi": "Tuyến đường vòng mới nhằm mục đích giảm bớt tình trạng tắc nghẽn giao thông.",
        "synonyms": "relieve, ease, mitigate",
        "occurrences": 10
    },
    {
        "word": "proficiency",
        "phonetic": "/prəˈfɪʃ.ən.si/",
        "pos": "noun",
        "meaning_vi": "Trình độ thành thạo cao",
        "cefr_level": "C1",
        "skill": "writing",
        "category": "Education & Learning",
        "example_en": "High English proficiency opens up global career opportunities.",
        "example_vi": "Trình độ tiếng Anh thành thạo cao mở ra các cơ hội nghề nghiệp toàn cầu.",
        "synonyms": "fluency, mastery",
        "occurrences": 15
    },
    {
        "word": "meticulous",
        "phonetic": "/məˈtɪk.jə.ləs/",
        "pos": "adjective",
        "meaning_vi": "Tỉ mỉ, vô cùng cẩn thận",
        "cefr_level": "C1",
        "skill": "speaking",
        "category": "Work & Business",
        "example_en": "He showed meticulous planning in completing the research.",
        "example_vi": "Anh ấy đã thể hiện sự lập kế hoạch tỉ mỉ trong việc hoàn thành nghiên cứu.",
        "synonyms": "thorough, precise",
        "occurrences": 9
    },
    {
        "word": "inevitable",
        "phonetic": "/ɪnˈev.ɪ.tə.bəl/",
        "pos": "adjective",
        "meaning_vi": "Không thể tránh khỏi, tất yếu",
        "cefr_level": "C1",
        "skill": "reading",
        "category": "Work & Business",
        "example_en": "Change is an inevitable part of career advancement.",
        "example_vi": "Sự thay đổi là một phần tất yếu của sự thăng tiến nghề nghiệp.",
        "synonyms": "unavoidable, certain",
        "occurrences": 11
    },
    {
        "word": "sophisticated",
        "phonetic": "/səˈfɪs.tɪ.keɪ.tɪd/",
        "pos": "adjective",
        "meaning_vi": "Tinh vi, phức tạp, cao cấp",
        "cefr_level": "C1",
        "skill": "reading",
        "category": "Technology & Science",
        "example_en": "Modern software relies on sophisticated security algorithms.",
        "example_vi": "Phần mềm hiện đại dựa trên các thuật toán bảo mật tinh vi.",
        "synonyms": "advanced, complex",
        "occurrences": 10
    },
    {
        "word": "ubiquitous",
        "phonetic": "/juːˈbɪk.wɪ.təs/",
        "pos": "adjective",
        "meaning_vi": "Phổ biến ở khắp mọi nơi",
        "cefr_level": "C2",
        "skill": "reading",
        "category": "Technology & Science",
        "example_en": "Smartphones have become ubiquitous in modern society.",
        "example_vi": "Điện thoại thông minh đã trở nên phổ biến ở khắp mọi nơi trong xã hội hiện đại.",
        "synonyms": "omnipresent, widespread",
        "occurrences": 7
    }
]


def seed_vocabulary_data(db: Session, force: bool = False):
    """Khởi tạo toàn bộ dữ liệu từ vựng B1 - C2 nâng cao chuẩn Aptis."""
    if force:
        db.query(Vocabulary).delete()
        db.commit()
    elif db.query(Vocabulary).count() > 0:
        return

    for item in APTIS_HIGH_LEVEL_VOCABULARY:
        v = Vocabulary(
            word=item["word"],
            phonetic=item.get("phonetic"),
            pos=item.get("pos"),
            meaning_vi=item["meaning_vi"],
            cefr_level=item.get("cefr_level", "B1"),
            skill=item.get("skill", "general"),
            category=item.get("category", "General"),
            example_en=item.get("example_en"),
            example_vi=item.get("example_vi"),
            synonyms=item.get("synonyms"),
            occurrences=item.get("occurrences", 1)
        )
        db.add(v)
    
    db.commit()
